exports.queries = {
    GET_STORE_LIST: 'SELECT STORE_ID, STORE_NAME, STORE_ADDRESS, STORE_CODE FROM BMS.STORE ',
    CREATE_STORE: 'INSERT INTO BMS.STORE(STORE_NAME, STORE_ADDRESS, STORE_CODE, CREATED_ON, CREATED_BY) VALUES($1, $2,$3,$4,$5 )',
 UPDATE_STORE: 'UPDATE BMS.STORE SET STORE_NAME=$1, STORE_ADDRESS=$2,  CREATED_ON=$3, CREATED_BY=$4 WHERE STORE_ID=$5 '

// , GET_ID:'SELECT STORE_ID FROM BMS.STORE '
,GET_CODE:'SELECT STORE_CODE FROM BMS.STORE ',
GET_ID:'SELECT COUNT(STORE_ID) FROM BMS.STORE WHERE STORE_ID = $1 ' ,
DELETE_STORE:'DELETE FROM BMS.STORE WHERE STORE_ID=$1' ,

}