exports.queries = {
    GET_STORE_LIST: 'SELECT STORE_ID, STORE_NAME, STORE_ADDRESS, STORE_CODE FROM BMS.STORE ',
    CREATE_STORE: 'INSERT INTO BMS.STORE(STORE_NAME, STORE_ADDRESS, STORE_CODE, CREATED_ON, CREATED_BY) VALUES($1, $2,$3,$4,$5 )'

}