exports.queries = {
    GET_STORE_LIST: 'SELECT STORE_ID, STORE_NAME, STORE_ADDRESS, STORE_CODE FROM BMS.STORE ',
    CREATE_STORE: 'INSERT INTO BMS.STORE(STORE_NAME, STORE_ADDRESS, STORE_CODE, CREATED_ON, CREATED_BY) VALUES($1, $2,$3,$4,$5 )',
    UPDATE_STORE: 'UPDATE BMS.STORE SET STORE_NAME=$1, STORE_ADDRESS=$2,  CREATED_ON=$3, CREATED_BY=$4 WHERE STORE_ID=$5 ',
    //  GET_CODE:'SELECT STORE_CODE FROM BMS.STORE ',
    GET_ID: 'SELECT COUNT(STORE_ID) FROM BMS.STORE WHERE STORE_ID = $1 ',
    DELETE_STORE: 'DELETE FROM BMS.STORE WHERE STORE_ID=$1',
    // ////////////////////////////////////////////////////////////////////////////////

    GET_BOOKS: 'SELECT BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_ISBN, BOOK_PAGES, STORE_CODE, CREATED_ON, CREATED_BY FROM BMS.BOOK',
    CREAT_BOOK: 'INSERT INTO BMS.BOOK (BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_ISBN, BOOK_PAGES, STORE_CODE, CREATED_ON, CREATED_BY) VALUES($1, $2,$3,$4,$5 , $6, $7, $8, $9)',
    GET_ID_BOOK: 'SELECT COUNT(BOOK_ID) FROM BMS.BOOK WHERE BOOK_ID = $1 ',
    UPDATE_BOOK: 'UPDATE BMS.BOOK SET BOOK_TITLE=$1, BOOK_DESCRIPTION=$2, BOOK_AUTHOR=$3, BOOK_PUBLISHER=$4, BOOK_ISBN=$5, BOOK_PAGES=$6, STORE_CODE=$7, CREATED_ON=$8, CREATED_BY=$9 WHERE BOOK_ID=$10',
    DELETE_BOOK: 'DELETE FROM BMS.BOOK WHERE BOOK_ID=$1',
    GET_BOOK_DETAILS: `SELECT BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_ISBN, BOOK_PAGES,BOOK.STORE_CODE , STORE.STORE_NAME ,STORE.STORE_ADDRESS 
    FROM BMS.BOOK
    INNER JOIN BMS.STORE ON BOOK.STORE_CODE =STORE.STORE_CODE 
    WHERE BOOK_ID=$1 ` ,
}